apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
             claimName: postgres-claim
      containers:
      - image: bitnami/postgresql:latest
        name: postgres
        volumeMounts:
         - mountPath: "/var/lib/postgresql/data/"
           name: postgres-volume
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER 
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres" 
        resources:
          requests:
            cpu: "0.2"
            memory: 400Mi



